---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: marcelocorreia/terraform

inputs:
  - name: dockerfile

run:
  dir: dockerfile
  path: terraform
  args: [ version ]


