resources:
  - name: dockerfile
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      paths: [Dockerfile]
      private_key: {{git_private_key}}
      username: {{github_user}}

  - name: docker_image
    type: docker-image
    source:
      repository: {{container_fullname}}
      email: {{docker_mail}}
      username: {{docker_user}}
      password: {{docker_password}}
      cache: true

  - name: github_release
    type: github-release
    source:
      user: {{github_user}}
      repository: {{git_repo}}
      access_token: {{github_token}}

jobs:
  - name: {{container_name}}
    serial: true
    plan:
      - get: dockerfile
        trigger: true
      - put: docker_image
        params:
          build: dockerfile
          tag: {{release_version}}
          tag_as_latest: true
      - put: github_release
        params:
          name: {{release_version}}
          tag: {{release_version}}